from typing import Any

vec3 = Any
vec2 = Any
mat3 = Any

def norm(value: Any) -> float: ...
def normalize(value: Any) -> Any: ...
def dot(a: Any, b: Any) -> Any: ...
def cross(a: Any, b: Any) -> Any: ...
def angle_between(a: Any, b: Any) -> float: ...
def rotation(value: Any) -> Any: ...
def xy(value: Any) -> Any: ...
def sgn(value: Any) -> float: ...
def look_at(direction: Any, up: Any) -> Any: ...
