from typing import Any


class Aerial:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def step(self, dt: float) -> None: ...


class Drive:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    @staticmethod
    def max_turning_curvature(speed: float) -> float: ...
    def step(self, dt: float) -> None: ...


class Reorient:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def step(self, dt: float) -> None: ...


class Wavedash:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def step(self, dt: float) -> None: ...


class Dodge:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def step(self, dt: float) -> None: ...

